<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_select</name>
   <tag></tag>
   <elementGuidId>59409d55-219e-4d2e-a143-299f633906d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#widget_1_transfer_receiver</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
